# Generated by Django 4.1.4 on 2022-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("tbsp", "tablespoon"),
                            ("tsp", "teaspoon"),
                            ("cup", "cup"),
                            ("qt", "quart"),
                            ("pt", "pint"),
                            ("gal", "gallon"),
                        ],
                        default="tsp",
                        max_length=4,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
